export const FETCHING_DATA = "FETCHING_DATA";

export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";

export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";

export const FILTER_CALLS_BY_AGENTS = "FILTER_CALLS_BY_AGENTS";

export const FILTER_CALLS_BY_DURATION = "FILTER_CALLS_BY_DURATION";
export const UPDATE_NEXT_CALL_LABEL_SELECTION = "UPDATE_NEXT_CALL_LABEL_SELECTION";
export const SELECT_OP = "SELECT_OP";
export const HANDLE_SORT = "HANDLE_SORT";
export const HANDLE_PAGINATION = "HANDLE_PAGINATION";
export const UPDATE_PAGE_SIZE = "UPDATE_PAGE_SIZE";
